name    'puppet-es'
version '1.0.0'
source 'https://github.com/meltwater/puppet-es'
author 'meltwater'
license 'Apache License, Version 2.0'
summary 'Elastic Search Defined Type'
description 'This defined type provides a way to use multiple Elastic Search instances on a single machine.'
project_page 'https://github.com/meltwater/puppet-es'

dependency 'puppetlabs/stdlib', '>= 2.2.0'
dependency 'camptocamp-archive'
